#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    prog = bld.new_task_gen('cxx', 'program')
    prog.includes = './headers'
    prog.source = 'main.cpp'
    prog.env.append_value("CXXFLAGS", "-O3  -march=native -Wall")
    prog.uselib = ['JACK', 'SNDFILE', 'GTK2', 'BOOST']
    prog.target = 'guitarix'
    prog.chmod=0755
    prog.install_path = bld.env['BINDIR']

