// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GXWMM_TOGGLEIMAGE_H
#define _GXWMM_TOGGLEIMAGE_H


#include <glibmm/ustring.h>
#include <sigc++/sigc++.h>

/*
 * Copyright (C) 2009, 2010 Hermann Meyer, James Warden, Andreas Degert
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <gtkmm/misc.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GxToggleImage GxToggleImage;
typedef struct _GxToggleImageClass GxToggleImageClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gxw
{ class ToggleImage_Class; } // namespace Gxw
namespace Gxw {


class ToggleImage: public Gtk::Misc {
	public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef ToggleImage CppObjectType;
  typedef ToggleImage_Class CppClassType;
  typedef GxToggleImage BaseObjectType;
  typedef GxToggleImageClass BaseClassType;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  virtual ~ToggleImage();

#ifndef DOXYGEN_SHOULD_SKIP_THIS

private:
  friend class ToggleImage_Class;
  static CppClassType toggleimage_class_;

  // noncopyable
  ToggleImage(const ToggleImage&);
  ToggleImage& operator=(const ToggleImage&);

protected:
  explicit ToggleImage(const Glib::ConstructParams& construct_params);
  explicit ToggleImage(GxToggleImage* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GtkObject.
  GxToggleImage*       gobj()       { return reinterpret_cast<GxToggleImage*>(gobject_); }

  ///Provides access to the underlying C GtkObject.
  const GxToggleImage* gobj() const { return reinterpret_cast<GxToggleImage*>(gobject_); }


public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


private:

	public:
	ToggleImage();
	
  void set_base_name(const Glib::ustring& p1);
	
  Glib::ustring get_base_name();
	#ifdef GLIBMM_PROPERTIES_ENABLED
/** Base name of the image, append '_on' and '_off' for the stock names.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy< Glib::ustring > property_base_name() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** Base name of the image, append '_on' and '_off' for the stock names.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< Glib::ustring > property_base_name() const;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** The id of the linked variable.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy< Glib::ustring > property_var_id() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** The id of the linked variable.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly< Glib::ustring > property_var_id() const;
#endif //#GLIBMM_PROPERTIES_ENABLED


};

} // namespace Gxw


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gxw::ToggleImage
   */
  Gxw::ToggleImage* wrap(GxToggleImage* object, bool take_copy = false);
} //namespace Glib


#endif /* _GXWMM_TOGGLEIMAGE_H */

