// Generated by gmmproc 2.60.0 -- DO NOT MODIFY!
#ifndef _GXWMM_RADIOBUTTON_P_H
#define _GXWMM_RADIOBUTTON_P_H


#include <gtkmm/private/radiobutton_p.h>

#include <glibmm/class.h>

namespace Gxw
{

class RadioButton_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  using CppObjectType = RadioButton;
  using BaseObjectType = GxRadioButton;
  using BaseClassType = GxRadioButtonClass;
  using CppClassParent = Gtk::RadioButton_Class;
  using BaseClassParent = GtkRadioButtonClass;

  friend class RadioButton;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.

  //Callbacks (virtual functions):
};


} // namespace Gxw


#endif /* _GXWMM_RADIOBUTTON_P_H */

