#!/usr/bin/env python
# encoding: utf-8

import sys, os, TaskGen, ctypes

def configure(conf):
    pass

def build(bld):
    bundle = 'gxts9.lv2'
    
    src = ['gxts9.cpp'
           ]
    incl = ['./']
    lib = []
    if sys.platform.startswith("linux"):
        lib.append('dl')
    uselib = ['LV2CORE']
    cxxflag =[]
    if not bld.env['OPT'] and bld.env['SSE2']:
        cxxflag = [ "-msse2", "-mfpmath=sse"]
    lv2_effects = bld(
        features='cxx cshlib ',
        includes = incl,
        lib = lib,
        uselib = uselib,
        obj_ext  = '_4.o',
        cxxflags = cxxflag,
        defines  = ["LV2_SO"],
        target   = 'gxts9',
        source   = src,
        install_path = '${LV2DIR}/%s' % bundle,
        chmod = 0o755,
        )
    lv2_effects.env['shlib_PATTERN'] = '%s.so'
    
    if bld.env['LV2GUI']:
        uselib_local4 = []
        libpath4 = []
        lib4 = []
        incl4 = ['../../../libgxwmm','../../../libgxw','../']
        if sys.platform.startswith("linux"):
            lib4.append('dl')
        if bld.env["GX_LIB_SHARED"]:
            lib4 += ['gxwmm','gxw']
            libpath4 += [bld.path.find_dir("../../../libgxw/gxw").bldpath(bld.env),
                        bld.path.find_dir("../../../libgxwmm/gxwmm").bldpath(bld.env)]
        else:
            uselib_local4 += ['gxwmm','gxw']
        
        lv2_effetcs_gui = bld(
            features='cxx cshlib ',
            includes = incl4,
            lib = lib4,
            uselib = 'LV2CORE GTKMM',
            libpath = libpath4,
            uselib_local = uselib_local4,
            linkflags = '-Wl,-z,nodelete',
            defines  = ["LV2_GUI"],
            target   = 'gxts9_gui',
            source   = 'widget.cpp gxts9_gui.cpp',
            install_path = '${LV2DIR}/%s' % bundle,
            chmod = 0o755,
            )
        lv2_effetcs_gui.env['shlib_PATTERN'] = '%s.so'

    
    install_path = '${LV2DIR}/%s' % bundle,
    if bld.env['NOMODGUI']:
        bld.install_files('${LV2DIR}/gxts9.lv2', bld.path.ant_glob('*.ttl', excl=['modgui.ttl']), relative_trick=True)
    else:
        bld.install_files('${LV2DIR}/gxts9.lv2', bld.path.ant_glob('*.ttl'), relative_trick=True)
        bld.install_files('${LV2DIR}/gxts9.lv2', bld.path.ant_glob('modgui/**/*'), relative_trick=True)
