#!/usr/bin/env python
# encoding: utf-8

import sys

def configure(conf):
    pass

def build(bld):
    bundle = 'gx_jcm800pre.lv2'

    src = ['gx_jcm800pre.cpp',
           ]
    incl = ['../faust','./', '../DSP']
    lib = []
    if sys.platform.startswith("linux"):
        lib.append('dl')
    uselib = ['LV2CORE', "EIGEN3", 'ZITA_CONVOLVER', 'GX_RESAMPLER']
    cxxflag =[]
    if not bld.env['OPT'] and bld.env['SSE2']:
        cxxflag = [ "-msse2", "-mfpmath=sse"]
    lv2_effects = bld.shlib(
        includes = incl,
        lib = lib,
        use = uselib,
        obj_ext  = '_24.o',
        cxxflags = cxxflag,
        defines  = ["LV2_SO"],
        target   = 'gx_jcm800pre',
        source   = src,
        install_path = '${LV2DIR}/%s' % bundle,
        chmod = 0o755,
        )
    lv2_effects.env['cxxshlib_PATTERN'] = '%s.so'

    if bld.env['LV2GUI']:
        libpath1 = []
        lib1 = []
        incl = []
        if sys.platform.startswith("linux"):
            lib1.append('dl')

        lv2_plugin_gui = bld.shlib(
            includes = incl,
            lib = lib1,
            libpath = libpath1,
            use = ['gxwmm','LV2CORE','GTKMM'],
            linkflags = '-Wl,-z,nodelete',
            defines  = ["LV2_GUI"],
            target   = 'gx_jcm800pre_gui',
            source   = 'widget.cpp gx_jcm800pre_gui.cpp',
            install_path = '${LV2DIR}/%s' % bundle,
            chmod = 0o755,
            )
        lv2_plugin_gui.env['cxxshlib_PATTERN'] = '%s.so'


    install_path = '${LV2DIR}/%s' % bundle,
    if bld.env['MODGUI']:
        bld.install_files('${LV2DIR}/gx_jcm800pre.lv2', bld.path.ant_glob('*.ttl'), relative_trick=True)
        bld.install_files('${LV2DIR}/gx_jcm800pre.lv2', bld.path.ant_glob('modgui/**/*'), relative_trick=True)
    else:
        bld.install_files('${LV2DIR}/gx_jcm800pre.lv2', bld.path.ant_glob('*.ttl', excl=['modgui.ttl']), relative_trick=True)
