#! /bin/dash
dir="`dirname "$0"`"
export GLADE_CATALOG_SEARCH_PATH="$dir/../glade-gxw"
export GLADE_MODULE_SEARCH_PATH="$dir/../build/glade-gxw"
export LD_LIBRARY_PATH="$GLADE_MODULE_SEARCH_PATH:$dir/../build/libgxw/gxw"
exec glade "$@"
