#!/usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gx_amp'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gxamp.cpp', 'gx_amp.cc', 'gx_tonestack.cc'],
        includes = ['../faust','./', '../DSP', '../DSP/tube_tables'],
        use = ['LV2CORE','GLIBMM','GX_CONVOLVER'],
        ldscript = 'gx_amp.lds',
        mapfile = "gx_amp.map",
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = 'widget.cpp gxamp_gui.cpp',
        use = ['gxwmm','LV2CORE','GTKMM'],
        )
