#! /bin/bash

lv2liste=$(lv2ls |grep guitarix.sourceforge);
result=$(zenity  --list $lv2liste --column "Guitarix LV2 plugs" \
--width=600 --height=300 --title="Guitarix LV2 " \
 --text="select a guitarix lv2 plugin to run with jalv.gtk")

if [ $result  ]
then
jalv.gtk $result 
fi
