#!/usr/bin/env python
# encoding: utf-8

import os, re

def sub_file(src_fname, dst_fname, lst):

    f = open(src_fname, 'rU')
    txt = f.read()
    f.close()

    for (key, val) in lst:
        re_pat = re.compile(key, re.M)
        txt = re_pat.sub(val, txt)

    f = open(dst_fname, 'w')
    f.write(txt)
    f.close()

def append_sse_flags():
    cpu_model = None
    x86_flags = None
    try:
        for line in open("/proc/cpuinfo"):
            if cpu_model is None:
                if line.startswith("model name"):
                    cpu_model = line.split(":",1)[1].strip()
            elif x86_flags is None:
                if line.startswith("flags"):
                    x86_flags = line.split(":",1)[1].strip()
            else:
                break
    except IOError:
        pass
    if cpu_model is None or x86_flags is None:
        return False
    model = cpu_model.split()
    arch = os.uname()[4]

    if "sse2" in x86_flags:
        return True
    else:
        return False

def configure(conf):
    if not conf.env['NOSSE']:
        conf.env['SSE2'] = append_sse_flags()
    pa = '.so'

    conf.sub_config('gx_amp.lv2');
    sub_file('./src/LV2/gx_amp.lv2/manifest.ttl.in', './src/LV2/gx_amp.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gx_amp_stereo.lv2');
    sub_file('./src/LV2/gx_amp_stereo.lv2/manifest.ttl.in', './src/LV2/gx_amp_stereo.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxts9.lv2');
    sub_file('./src/LV2/gxts9.lv2/manifest.ttl.in', './src/LV2/gxts9.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gxbooster.lv2');
    sub_file('./src/LV2/gxbooster.lv2/manifest.ttl.in', './src/LV2/gxbooster.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_echo.lv2');
    sub_file('./src/LV2/gx_echo.lv2/manifest.ttl.in', './src/LV2/gx_echo.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_compressor.lv2');
    sub_file('./src/LV2/gx_compressor.lv2/manifest.ttl.in', './src/LV2/gx_compressor.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_expander.lv2');
    sub_file('./src/LV2/gx_expander.lv2/manifest.ttl.in', './src/LV2/gx_expander.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_tremolo.lv2');
    sub_file('./src/LV2/gx_tremolo.lv2/manifest.ttl.in', './src/LV2/gx_tremolo.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_zita_rev1.lv2');
    sub_file('./src/LV2/gx_zita_rev1.lv2/manifest.ttl.in', './src/LV2/gx_zita_rev1.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_flanger.lv2');
    sub_file('./src/LV2/gx_flanger.lv2/manifest.ttl.in', './src/LV2/gx_flanger.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_phaser.lv2');
    sub_file('./src/LV2/gx_phaser.lv2/manifest.ttl.in', './src/LV2/gx_phaser.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gx_chorus.lv2');
    sub_file('./src/LV2/gx_chorus.lv2/manifest.ttl.in', './src/LV2/gx_chorus.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))
    
    conf.sub_config('gxautowah.lv2');
    sub_file('./src/LV2/gxautowah.lv2/manifest.ttl.in', './src/LV2/gxautowah.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxpreamp.lv2');
    sub_file('./src/LV2/gxpreamp.lv2/manifest.ttl.in', './src/LV2/gxpreamp.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxpreamp.lv2/StereoAmp');
    sub_file('./src/LV2/gxpreamp.lv2/StereoAmp/manifest_stereo.ttl.in', './src/LV2/gxpreamp.lv2/StereoAmp/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxtilttone.lv2');
    sub_file('./src/LV2/gxtilttone.lv2/manifest.ttl.in', './src/LV2/gxtilttone.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxtubevibrato.lv2');
    sub_file('./src/LV2/gxtubevibrato.lv2/manifest.ttl.in', './src/LV2/gxtubevibrato.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxtubetremelo.lv2');
    sub_file('./src/LV2/gxtubetremelo.lv2/manifest.ttl.in', './src/LV2/gxtubetremelo.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxtubedelay.lv2');
    sub_file('./src/LV2/gxtubedelay.lv2/manifest.ttl.in', './src/LV2/gxtubedelay.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gx_studiopre.lv2');
    sub_file('./src/LV2/gx_studiopre.lv2/manifest.ttl.in', './src/LV2/gx_studiopre.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gx_studiopre_st.lv2');
    sub_file('./src/LV2/gx_studiopre_st.lv2/manifest.ttl.in', './src/LV2/gx_studiopre_st.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

    conf.sub_config('gxechocat.lv2');
    sub_file('./src/LV2/gxechocat.lv2/manifest.ttl.in', './src/LV2/gxechocat.lv2/manifest.ttl', (('@LIB_EXT@', '%s' % pa), ))

def build(bld):
    # faust folder keep of for now
    bld.add_subdirs('faust')
    bld.add_subdirs('gx_amp.lv2')
    bld.add_subdirs('gx_amp_stereo.lv2')
    bld.add_subdirs('gxts9.lv2')
    bld.add_subdirs('gxbooster.lv2')
    bld.add_subdirs('gx_echo.lv2')
    bld.add_subdirs('gx_tremolo.lv2')
    bld.add_subdirs('gx_compressor.lv2')
    bld.add_subdirs('gx_expander.lv2')
    bld.add_subdirs('gx_zita_rev1.lv2')
    bld.add_subdirs('gx_flanger.lv2')
    bld.add_subdirs('gx_phaser.lv2')
    bld.add_subdirs('gx_chorus.lv2')
    bld.add_subdirs('gx_delay.lv2')
    bld.add_subdirs('gx_reverb.lv2')
    bld.add_subdirs('gxautowah.lv2')
    bld.add_subdirs('gxpreamp.lv2')
    bld.add_subdirs('gxpreamp.lv2/StereoAmp')
    bld.add_subdirs('gxtilttone.lv2')
    bld.add_subdirs('gxtubevibrato.lv2')
    bld.add_subdirs('gxtubetremelo.lv2')
    bld.add_subdirs('gxtubedelay.lv2')
    bld.add_subdirs('gx_studiopre.lv2')
    bld.add_subdirs('gx_studiopre_st.lv2')
    bld.add_subdirs('gxechocat.lv2')

    gx_ampstyledir = bld.path.find_dir( 'GUI' ) ;
    bld.install_files(bld.env['GX_LV2_STYLE_DIR'], gx_ampstyledir.ant_glob('**/*.png'),cwd=gx_ampstyledir, chmod=0o644, relative_trick=True)
    bld.install_files(bld.env['GX_LV2_STYLE_DIR'], gx_ampstyledir.ant_glob('**/*.rc'),cwd=gx_ampstyledir, chmod=0o644, relative_trick=True)

