#!/usr/bin/env python
# encoding: utf-8

import sys

def configure(conf):
    pass

def build(bld):
    bundle = 'gx_amp_stereo.lv2'

    src = ['gxamp_stereo.cpp',
           'gx_amp_stereo.cc',
           'gx_tonestack_stereo.cc',
           ]
    incl = ['../faust','./', '../DSP', '../DSP/tube_tables']
    lib = []
    if sys.platform.startswith("linux"):
        lib.append('dl')
    uselib = ['LV2CORE','GLIBMM','GX_CONVOLVER']
    cxxflag =[]
    ldscript = bld.path.find_resource('gxamp_stereo.lds')
    mapfile = bld.path.find_or_declare("gxamp_stereo.map")
    if not bld.env['OPT'] and bld.env['SSE2']:
        cxxflag = [ "-msse2", "-mfpmath=sse"]
    lv2_plugin = bld.shlib(
        includes = incl,
        lib = lib,
        use = uselib,
        obj_ext  = '_13.o',
        cxxflags = cxxflag,
        defines  = ["LV2_SO"],
        target   = 'gx_amp_stereo',
        source   = src,
        install_path = '${LV2DIR}/%s' % bundle,
        chmod = 0o755,
        ldflags = ['-Wl,%s,-Map=%s' % (ldscript.bldpath(),mapfile.bldpath())],
        )
    bld.add_manual_dependency(bld.path.find_or_declare(lv2_plugin.target), ldscript)
    lv2_plugin.env['cxxshlib_PATTERN'] = '%s.so'

    if bld.env['LV2GUI']:
        libpath1 = []
        lib1 = []
        incl = []
        if sys.platform.startswith("linux"):
            lib1.append('dl')

        lv2_plugin_gui = bld.shlib(
            includes = incl,
            lib = lib1,
            libpath = libpath1,
            use = ['gxwmm', 'LV2CORE', 'GTKMM'],
            linkflags = '-Wl,-z,nodelete',
            defines  = ["LV2_GUI"],
            target   = 'gx_amp_stereo_gui',
            source   = 'widget_stereo.cpp gxamp_stereo_gui.cpp',
            install_path = '${LV2DIR}/%s' % bundle,
            chmod = 0o755,
            )
        lv2_plugin_gui.env['cxxshlib_PATTERN'] = '%s.so'


    install_path = '${LV2DIR}/%s' % bundle,
    if bld.env['MODGUI']:
        bld.install_files('${LV2DIR}/gx_amp_stereo.lv2', bld.path.ant_glob('*.ttl'), relative_trick=True)
        bld.install_files('${LV2DIR}/gx_amp_stereo.lv2', bld.path.ant_glob('modgui/**/*'), relative_trick=True)
    else:
        bld.install_files('${LV2DIR}/gx_amp_stereo.lv2', bld.path.ant_glob('*.ttl', excl=['modgui.ttl']), relative_trick=True)
