#!/usr/bin/env python
# encoding: utf-8

import Build
import os

def configure(conf):
    pass

def build(bld):
    bld.env['GX_LIB'] = 'guitarix'

    soname= 'lib' + bld.env['GX_LIB'] +'.so'
    sonamever= soname + '.' + bld.env['GX_VERSION']
    absname = os.path.join(bld.env['LIBDIR'], soname)
    absnamever = os.path.join(bld.env['LIBDIR'], sonamever)

    bld.new_task_gen(
        features = 'cxx cshlib',
        cxxflags = bld.env['CXXFLAGS'],
        source = ['crybaby.cpp',
                  'distortion.cpp',
                  'echo.cpp',
                  'freeverb.cpp',
                  'impulseresponse.cpp',
                  'monoamp.cpp',
                  'monocompressor.cpp'],
        target = bld.env['GX_LIB'],
        install_path=None
    )
        
    bld.install_as(absnamever, soname, chmod=0755)
    bld.symlink_as(absname, sonamever)

