#!/bin/sh

# check that guitarix is installed
gx_app=guitarix-0.4.4
gx_ok=`which $gx_app`

if test $? -ne 0; then
    echo "Could not find $gx_app in PATH, giving up ..."
    exit 1
fi

# set it up
export GUITARIX2JACK_INPUTS=system:capture_1
export GUITARIX2JACK_OUTPUTS1=system:playback_1
export GUITARIX2JACK_OUTPUTS2=system:playback_2

GUITARIX_RC_PATH=/usr/local/share/guitarix
if test -d /usr/share/guitarix; then
    GUITARIX_RC_PATH=/usr/share/guitarix
fi

RCSTYLE=$GUITARIX_RC_PATH/guitarix_black.rc

# launch it
$gx_app -r ${RCSTYLE} &

# sleep and exit
sleep 5
exit 

