# -*- python -*-
# -*- coding: utf-8 -*-

from waflib import Options

def options(opt):
    grp = opt.get_option_group("Guitarix Widget Library")
    grp.add_option('--glade-support',
                   action='store_const',
                   default=False,
                   const=True,
                   help=('build support for Glade / GtkBuilder (Developers only!!)'),
                   )
    grp.add_option('--glade-catalog-dir',
                   type='string',
                   default='/usr/share/glade3/catalogs',
                   help='Glade catalog dir [Default: %default]')
    grp.add_option('--glade-modules-dir',
                   type='string',
                   default='/usr/lib/glade3/modules',
                   help='Glade modules dir [Default: %default]')

def configure(conf):
    if Options.options.glade_support:
        conf.env.GX_GLADE_SUPPORT = True
        conf.env.GXW_SHARED = True
        conf.env.GXW_SHARED_INSTALL = True
        conf.env.GLADE_CATALOG_DIR = Options.options.glade_catalog_dir
        conf.env.GLADE_MODULES_DIR = Options.options.glade_modules_dir
        
def build(bld):
    if not bld.env.GX_GLADE_SUPPORT:
        return
    bld.recurse("glade-icons")
    bld.shlib(
        ccflags = bld.env.CXXFLAGS,
        use = ['GTK2','gxw'],
        source = ['glade-gxw.c'],
        target = 'gladegx',
        includes = ['..'],
        install_path = bld.env.GLADE_MODULES_DIR,
        )

    bld.install_files(bld.env.GLADE_CATALOG_DIR, "gxw.xml", chmod=0o644)
