#!/usr/bin/env python
# encoding: utf-8

import Build

# start each filename with a space
pixmap_files  = ''
pixmap_files += ' gx_head.png' 
pixmap_files += ' gx_head-midi.png'
pixmap_files += ' gx_head-warn.png'
pixmap_files += ' gx_splash.png'

def configure(conf):
    pass

def build(bld):
    bld.install_files(bld.env['GX_PIXMAPS_DIR'], pixmap_files, chmod=0o644)
