#!/usr/bin/env python
# encoding: utf-8

gxstyle_files = [
    'gx_head_Guitarix.rc',
    'background1.png',
    'background2.png',

    'clear.rc',
    'tactile_knob_large_151f.png',
    'tactile_knob_small_99f.png',
    'tactile_knob_medium_151f.png',
    'tactile_wheel_101f.png',

    'stereo.png',
    'bypass.svg',
    'factory.png',
    'mute.svg',
    'readonly.png',
    'scratch.png',
    'versiondiff.png',
    'playhead.png',
    'simplelevelslider.png',

    'switch_on.png',
    'switch_mid_off.png',
    'switch_mid_on.png',
    'switch_off.png',
    'rack_expand.png',
    'rack_shrink.png',
    'rack_preset.png',
    'rack_preset.png',
    'insert.png',
    'hslider.png',
    'logo.png',
    'logo_orange.png',
    'logo_white.png',
    'handle_left.png',
    'handle_right.png',

    # knobs
    'knob_small.png',
    'knob_small_r.png',
    'knob_mid.png',
    'knob_big.png',
    
    ###COPPER THEME
    'gx_head_Copper.rc',
    'copper.png',
    
    ###LAVENDER THEME
    'gx_head_Lavender.rc',
    'lavender.png',
    
    ###SKY THEME
    'gx_head_Sky.rc',
    'sky.png',
    
    ###OLIVE THEME
    'gx_head_Olive.rc',
    'olive.png',
    
    ###ALUMINIUM THEME
    'gx_head_Aluminium.rc',
    'aluminium.png',
    
    ###OAK THEME
    'gx_head_Oak.rc',
    'oak1.png',
    'oak2.png',
    
    ###BURL THEME
    'gx_head_Burl.rc',
    'burl1.png',
    'burl2.png',
    
    ###WHITE OAK THEME
    'gx_head_White_Oak.rc',
    'oak_white.png',
    #'oak2.png',
    
    ###GUITARIX OAK THEME
    'gx_head_Guitarix_Oak.rc',
    'oak_green.png',
    #'oak2.png',
    
    ###DARK THEME
    'gx_head_Dark.rc',
    'dark.png',
    
    ###CAMOUFLAGE THEME
    'gx_head_Camouflage.rc',
    'camouflage.png',
    
     ]

def configure(conf):
    pass

def build(bld):
    bld.install_files(bld.env['GX_STYLE_DIR'], gxstyle_files, chmod=0o644)
