/*
 * Copyright (C) 2012 Hermann Meyer, Andreas Degert, Pete Shorthose, Steve Poskitt
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * --------------------------------------------------------------------------
 */


////////////////////////////// LOCAL INCLUDES //////////////////////////

#include "gx_common.h"      // faust support and denormal protection (SSE)
#include "gx_moog.h"        // define struct PortIndex
#include "gx_pluginlv2.h"   // define struct PluginLV2
#include "moog.cc"    // dsp class generated by faust -> dsp2cc

////////////////////////////// PLUG-IN CLASS ///////////////////////////

namespace moog {

class Gx_moog_
{
private:
  // pointer to buffer
  float*      output;
  float*      input;
  float*      output1;
  float*      input1;
  // pointer to dsp class
  PluginLV2*  moog;
  // private functions
  inline void run_dsp_(uint32_t n_samples);
  inline void connect_(uint32_t port,void* data);
  inline void init_dsp_(uint32_t rate);
  inline void connect_all__ports(uint32_t port, void* data);
  inline void activate_f();
  inline void clean_up();
  inline void deactivate_f();

public:
  // LV2 Descriptor
  static const LV2_Descriptor descriptor;
  // static wrapper to private functions
  static void deactivate(LV2_Handle instance);
  static void cleanup(LV2_Handle instance);
  static void run(LV2_Handle instance, uint32_t n_samples);
  static void activate(LV2_Handle instance);
  static void connect_port(LV2_Handle instance, uint32_t port, void* data);
  static LV2_Handle instantiate(const LV2_Descriptor* descriptor,
                                double rate, const char* bundle_path,
                                const LV2_Feature* const* features);
  Gx_moog_();
  ~Gx_moog_();
};

// constructor
Gx_moog_::Gx_moog_() :
  output(NULL),
  input(NULL),
  moog(moog::plugin()) {};

// destructor
Gx_moog_::~Gx_moog_()
{
  // just to be sure the plug have given free the allocated mem
  // it didn't hurd if the mem is already given free by clean_up()
  if (moog->activate_plugin !=0)
    moog->activate_plugin(false, moog);
  // delete DSP class
  moog->delete_instance(moog);
};

///////////////////////// PRIVATE CLASS  FUNCTIONS /////////////////////

void Gx_moog_::init_dsp_(uint32_t rate)
{
  AVOIDDENORMALS(); // init the SSE denormal protection
  moog->set_samplerate(rate, moog); // init the DSP class
}

// connect the Ports used by the plug-in class
void Gx_moog_::connect_(uint32_t port,void* data)
{
  switch ((PortIndex)port)
    {
    case EFFECTS_OUTPUT:
      output = static_cast<float*>(data);
      break;
    case EFFECTS_INPUT:
      input = static_cast<float*>(data);
      break;
    case EFFECTS_OUTPUT1:
      output1 = static_cast<float*>(data);
      break;
    case EFFECTS_INPUT1:
      input1 = static_cast<float*>(data);
      break;
    default:
      break;
    }
}

void Gx_moog_::activate_f()
{
  // allocate the internal DSP mem
  if (moog->activate_plugin !=0)
    moog->activate_plugin(true, moog);
}

void Gx_moog_::clean_up()
{
  // delete the internal DSP mem
  if (moog->activate_plugin !=0)
    moog->activate_plugin(false, moog);
}

void Gx_moog_::deactivate_f()
{
  // delete the internal DSP mem
  if (moog->activate_plugin !=0)
    moog->activate_plugin(false, moog);
}

void Gx_moog_::run_dsp_(uint32_t n_samples)
{
  moog->stereo_audio(static_cast<int>(n_samples), input, input1, output, output1, moog);
}

void Gx_moog_::connect_all__ports(uint32_t port, void* data)
{
  // connect the Ports used by the plug-in class
  connect_(port,data); 
  // connect the Ports used by the DSP class
  moog->connect_ports(port,  data, moog);
}

////////////////////// STATIC CLASS  FUNCTIONS  ////////////////////////

LV2_Handle 
Gx_moog_::instantiate(const LV2_Descriptor* descriptor,
                            double rate, const char* bundle_path,
                            const LV2_Feature* const* features)
{
  // init the plug-in class
  Gx_moog_ *self = new Gx_moog_();
  if (!self)
    {
      return NULL;
    }

  self->init_dsp_((uint32_t)rate);

  return (LV2_Handle)self;
}

void Gx_moog_::connect_port(LV2_Handle instance, 
                                   uint32_t port, void* data)
{
  // connect all ports
  static_cast<Gx_moog_*>(instance)->connect_all__ports(port, data);
}

void Gx_moog_::activate(LV2_Handle instance)
{
  // allocate needed mem
  static_cast<Gx_moog_*>(instance)->activate_f();
}

void Gx_moog_::run(LV2_Handle instance, uint32_t n_samples)
{
  // run dsp
  static_cast<Gx_moog_*>(instance)->run_dsp_(n_samples);
}

void Gx_moog_::deactivate(LV2_Handle instance)
{
  // free allocated mem
  static_cast<Gx_moog_*>(instance)->deactivate_f();
}

void Gx_moog_::cleanup(LV2_Handle instance)
{
  // well, clean up after us
  Gx_moog_* self = static_cast<Gx_moog_*>(instance);
  self->clean_up();
  delete self;
}

const LV2_Descriptor Gx_moog_::descriptor =
{
  GXPLUGIN_URI "#_moog_",
  Gx_moog_::instantiate,
  Gx_moog_::connect_port,
  Gx_moog_::activate,
  Gx_moog_::run,
  Gx_moog_::deactivate,
  Gx_moog_::cleanup,
  NULL
};

} // end namespace moog

////////////////////////// LV2 SYMBOL EXPORT ///////////////////////////

extern "C"
LV2_SYMBOL_EXPORT
const LV2_Descriptor*
lv2_descriptor(uint32_t index)
{
  switch (index)
    {
    case 0:
      return &moog::Gx_moog_::descriptor;
    default:
      return NULL;
    }
}

///////////////////////////// FIN //////////////////////////////////////
