b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("drive"), "Distortion");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("drive"), "Distortion");
    b.create_small_rackknobr(PARAM("tone"), "Filter");
    b.create_small_rackknobr(PARAM("level"), "Volume");
    b.insertSpacer(68);
b.closeBox();
