b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Attack"), "Attack");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("Attack"), "Attack");
    b.create_small_rackknobr(PARAM("Smooth"), "Smooth");
    b.create_small_rackknobr(PARAM("Level"), "Level");
    b.insertSpacer(68);
b.closeBox();
