b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Volume"), "Volume");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("Intensity"), "Intensity");
    b.create_small_rackknobr(PARAM("Volume"), "Volume");
    b.insertSpacer(68);
b.closeBox();
