b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Drive"), "Drive");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("Drive"), "Drive");
    b.insertSpacer(68);
b.closeBox();
