b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Fuzz"), "Fuzz");
b.closeBox();
b.openHorizontalBox("");
    b.create_small_rackknobr(PARAM("Gate"), "Gate");
    b.create_small_rackknobr(PARAM("Fuzz"), "Fuzz");
    b.create_small_rackknobr(PARAM("Tone"), "Tone");
    b.create_small_rackknobr(PARAM("wet_dry"), "Dry/Wet");
    b.create_small_rackknobr(PARAM("Level"), "Level");
b.closeBox();
