b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Fuzz"), "Fuzz");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer();
    b.insertSpacer();
    b.create_small_rackknobr(PARAM("Fuzz"), "Fuzz");
    b.create_small_rackknobr(PARAM("Level"), "Level");
    b.insertSpacer();
b.closeBox();
