b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Fuzz"), "Fuzz");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("Fuzz"), "Fuzz");
    b.create_small_rackknobr(PARAM("Level"), "Level");
    b.insertSpacer(68);
b.closeBox();
