b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Fuzz"), N_("Fuzz"));
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("Fuzz"), N_("Fuzz"));
    b.create_small_rackknobr(PARAM("Level"), N_("Level"));
    b.insertSpacer(68);
b.closeBox();
