b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("hotpotz"), "Wah");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("hotpotz"), "Wah");
    b.create_small_rackknobr(PARAM("Volume"), "Volume");
    b.insertSpacer(68);
b.closeBox();
