b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Volume"), N_("Volume"));
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer();
    b.insertSpacer();
    b.create_small_rackknobr(PARAM("Volume"), N_("Volume"));
    b.create_small_rackknobr(PARAM("Intensity"), N_("Intensity"));
    b.insertSpacer();
b.closeBox();
