b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("wet_dry"), "Dry/Wet");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer();
    b.insertSpacer();
    b.create_small_rackknobr(PARAM("wet_dry"), "Dry/Wet");
    b.create_small_rackknobr(PARAM("Volume"), "Volume");
    b.insertSpacer();
b.closeBox();
