b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Boost"), "Boost");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.insertSpacer(68);
    b.create_small_rackknobr(PARAM("Boost"), "Boost");
    b.insertSpacer(68);
b.closeBox();
