b.openHorizontalhideBox("");
    b.create_master_slider(PARAM("Boost"), "Boost");
b.closeBox();
b.openHorizontalBox("");
    b.insertSpacer();
    b.insertSpacer();
    b.insertSpacer();
    b.create_small_rackknobr(PARAM("Boost"), "Boost");
    b.insertSpacer();
b.closeBox();
