#! /usr/bin/env python
# encoding: utf-8


def options(opt):
    pass

def configure(conf):
    if not conf.env.LV2GUI:
        return
    opt = conf.options
    env = conf.env
    conf.check_cfg(package='cairo', args='--cflags --libs', uselib_store='CAIRO', mandatory=1)
    conf.check_cc(lib='X11', uselib_store='X11', mandatory=True) and \
    conf.check_cc( header_name = 'X11/Xlib.h', uselib_store = 'X11', mandatory=1)

def build(bld):
    if not (bld.env.LV2GUI):
        return

    sources = bld.path.ant_glob('*.cpp')
    sources += bld.path.ant_glob('widgets/*.cpp')
    sources += bld.path.ant_glob('dialogs/*.cpp')
    prog = bld(
        features=['cxx', 'cxxstlib'],
        name = 'xcairo',
        includes = ['.','./header','./header/widgets','./header/dialogs','./resources','./xdgmime'],
        export_includes = ['..'],
        source = sources+['./resources/resources.o'],
        uselib = ['X11', 'CAIRO'],
        cxxflags='-fPIC',
        target = 'xcairo',
        )
    prog.install_path = None

