


#include "valve.h"


class GxAmpFeedBack {
private:
	uint32_t fSamplingFreq;
	float 	fslider0;
	float	*fslider0_;
	double 	fRec0[2];
	int32_t 	iConst0;
	double 	fConst1;
	double 	fConst2;
	double 	fConst3;
	double 	fConst4;
	double 	fConst5;
	double 	fConst6;
	float 	fslider1;
	float	*fslider1_;
	double 	fRec8[2];
	double 	fConst7;
	double 	fConst8;
	double 	fConst9;
	double 	fConst10;
	double 	fConst11;
	double 	fConst12;
	double 	fConst13;
	double 	fConst14;
	double 	fConst15;
	double 	fConst16;
	double 	fConst17;
	double 	fConst18;
	double 	fConst19;
	double 	fConst20;
	double 	fConst21;
	double 	fConst22;
	double 	fConst23;
	double 	fConst24;
	double 	fConst25;
	double 	fConst26;
	double 	fConst27;
	double 	fConst28;
	double 	fConst29;
	double 	fConst30;
	double 	fConst31;
	double 	fConst32;
	double 	fConst33;
	double 	fConst34;
	double 	fConst35;
	double 	fConst36;
	float 	fslider2;
	float	*fslider2_;
	double 	fRec20[2];
	double 	fRec19[3];
	double 	fVec0[2];
	double 	fConst37;
	double 	fConst38;
	double 	fRec18[2];
	double 	fConst39;
	double 	fRec17[2];
	double 	fRec16[3];
	double 	fVec1[2];
	double 	fConst40;
	double 	fConst41;
	double 	fRec15[2];
	double 	fRec14[3];
	double 	fConst42;
	double 	fRec13[3];
	float 	fslider3;
	float	*fslider3_;
	double 	fConst43;
	double 	fConst44;
	double 	fConst45;
	double 	fConst46;
	double 	fRec24[2];
	double 	fRec23[3];
	double 	fVec2[2];
	double 	fConst47;
	double 	fConst48;
	double 	fRec22[2];
	double 	fRec21[3];
	double 	fConst49;
	double 	fConst50;
	double 	fConst51;
	double 	fConst52;
	double 	fRec28[2];
	double 	fRec27[3];
	double 	fConst53;
	double 	fRec26[3];
	double 	fRec25[3];
	double 	fRec30[2];
	double 	fRec29[3];
	double 	fVec3[2];
	double 	fConst54;
	double 	fRec12[2];
	double 	fConst55;
	double 	fConst56;
	double 	fConst57;
	double 	fConst58;
	double 	fRec31[2];
	double 	fRec11[3];
	double 	fConst59;
	double 	fRec10[2];
	double 	fConst60;
	double 	fConst61;
	double 	fConst62;
	double 	fConst63;
	double 	fRec34[2];
	double 	fRec33[3];
	double 	fRec32[2];
	float 	fslider4;
	float	*fslider4_;
	double 	fRec35[2];
	double 	fRec9[2];
	double 	fVec4[2];
	double 	fRec7[2];
	double 	fRec36[2];
	double 	fRec6[3];
	double 	fRec5[2];
	double 	fConst64;
	double 	fConst65;
	double 	fConst66;
	double 	fConst67;
	double 	fRec39[2];
	double 	fRec38[3];
	double 	fRec37[2];
	double 	fRec4[2];
	double 	fRec3[2];
	double 	fRec40[2];
	double 	fRec2[3];
	double 	fRec1[2];
	void clear_state_f();
	void init(uint32_t samplingFreq);
	void connect(uint32_t port,void* data);
public:
    
    void run_12ax7_f(uint32_t count, float *input0, float *output0);
    void run_12AT7_f(uint32_t count, float *input0, float *output0);
    void run_6DJ8_f(uint32_t count, float *input0, float *output0);
    static void clear_state_f_static(GxAmpFeedBack*);
	static void init_static(uint32_t samplingFreq, GxAmpFeedBack *p);
    static void connect_static(uint32_t port,void* data, GxAmpFeedBack *p);
	GxAmpFeedBack() {};
	~GxAmpFeedBack() {};
};
