#!/usr/bin/env python3
# encoding: utf-8

import sys, os, ctypes

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gx_fumaster'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gx_fumaster.cpp'],
        includes = ['../faust','./', '../DSP', '../DSP/tube_tables'],
        cxxflags=['-fvisibility=hidden','-Wl,-z,noexecstack','-Wl,-z,relro,-z,now','-Wl,--exclude-libs,ALL'],
        use = ['LV2CORE','FFTW3'],
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gx_fumaster_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources',],
        cxxflags=['-fvisibility=hidden','-Wl,-z,noexecstack','-Wl,-z,relro,-z,now','-Wl,--exclude-libs,ALL'],
        use = ['xcairo','X11', 'CAIRO','LV2CORE'],
        )
