#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    prog = bld.new_task_gen('cxx', 'program')
    prog.includes = './headers'
    prog.cxxflags= bld.env['CXXFLAGS']
    prog.source = 'main.cpp'
    prog.uselib = ['JACK', 'SNDFILE', 'GTK2', 'BOOST']
    prog.target = bld.env['BIN_NAME']
    prog.chmod=0755
    prog.install_path = bld.env['BINDIR']

