#!/usr/bin/env python
# encoding: utf-8

import sys, os, TaskGen, ctypes, wscript_helper

def configure(conf):
    pass

def build(bld):
    bundle = 'gxtuner.lv2'
    
    src = ['gxtuner.cpp',
           '../DSP/gx_resampler.cc'
           ]
    incl = ['../faust','./', '../DSP']
    lib = []
    if sys.platform.startswith("linux"):
        lib.append('dl')
    uselib = ['LV2CORE','GLIBMM']
    uselib.append('FFTW3')
    wscript_helper.add_zita_resampler(bld, uselib, src, incl, base="../..")
    if sys.platform.startswith("linux"):
        lib.append('dl')
    cxxflag =[]
    if not bld.env['OPT'] and bld.env['SSE2']:
        cxxflag = [ "-msse2", "-mfpmath=sse"]
    lv2_effects = bld(
        features='cxx cshlib ',
        includes = incl,
        lib = lib,
        uselib = uselib,
        obj_ext  = '_18.o',
        cxxflags = cxxflag,
        defines  = ["LV2_SO"],
        target   = 'gxtuner',
        source   = src,
        install_path = '${LV2DIR}/%s' % bundle,
        chmod = 0o755,
        )
    lv2_effects.env['shlib_PATTERN'] = '%s.so'
    
    uselib_local5 = []
    libpath5 = []
    lib5 = []
    incl5 = ['../../../libgxwmm','../../../libgxw','../']
    if sys.platform.startswith("linux"):
        lib5.append('dl')
    if bld.env["GX_LIB_SHARED"]:
        lib5 += ['gxwmm','gxw']
        libpath5 += [bld.path.find_dir("../../../libgxw/gxw").bldpath(bld.env),
                    bld.path.find_dir("../../../libgxwmm/gxwmm").bldpath(bld.env)]
    else:
        uselib_local5 += ['gxwmm','gxw']
    
    lv2_effetcs_gui = bld(
        features='cxx cshlib ',
        includes = incl5,
        lib = lib5,
        uselib = 'LV2CORE GTKMM',
        libpath = libpath5,
        uselib_local = uselib_local5,
        linkflags = '-Wl,-z,nodelete',
        defines  = ["LV2_GUI"],
        target   = 'gxtuner_gui',
        source   = 'widget.cpp gxtuner_gui.cpp',
        install_path = '${LV2DIR}/%s' % bundle,
        chmod = 0o755,
        )
    lv2_effetcs_gui.env['shlib_PATTERN'] = '%s.so'

    
    install_path = '${LV2DIR}/%s' % bundle,
    bld.install_files('${LV2DIR}/gxtuner.lv2', 'manifest.ttl')
    bld.install_files('${LV2DIR}/gxtuner.lv2', 'gxtuner.ttl')

