/*
 * Copyright (C) 2014 Guitarix project MOD project
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * --------------------------------------------------------------------------
 */


////////////////////////////// LOCAL INCLUDES //////////////////////////

#include "gx_common.h"      // faust support and denormal protection (SSE)
#include "gx_fuzzface.h"        // define struct PortIndex
#include "gx_pluginlv2.h"   // define struct PluginLV2
#include "fuzzface.cc"    // dsp class generated by faust -> dsp2cc

////////////////////////////// PLUG-IN CLASS ///////////////////////////

namespace fuzzface {

class Gx_fuzzface_
{
private:
  // pointer to buffer
  float*      output;
  float*      input;
  // pointer to dsp class
  PluginLV2*  fuzzface;
  // private functions
  inline void run_dsp_(uint32_t n_samples);
  inline void connect_(uint32_t port,void* data);
  inline void init_dsp_(uint32_t rate);
  inline void connect_all__ports(uint32_t port, void* data);
  inline void activate_f();
  inline void clean_up();
  inline void deactivate_f();

public:
  // LV2 Descriptor
  static const LV2_Descriptor descriptor;
  // static wrapper to private functions
  static void deactivate(LV2_Handle instance);
  static void cleanup(LV2_Handle instance);
  static void run(LV2_Handle instance, uint32_t n_samples);
  static void activate(LV2_Handle instance);
  static void connect_port(LV2_Handle instance, uint32_t port, void* data);
  static LV2_Handle instantiate(const LV2_Descriptor* descriptor,
                                double rate, const char* bundle_path,
                                const LV2_Feature* const* features);
  Gx_fuzzface_();
  ~Gx_fuzzface_();
};

// constructor
Gx_fuzzface_::Gx_fuzzface_() :
  output(NULL),
  input(NULL),
  fuzzface(fuzzface::plugin()) {};

// destructor
Gx_fuzzface_::~Gx_fuzzface_()
{
  // just to be sure the plug have given free the allocated mem
  // it didn't hurd if the mem is already given free by clean_up()
  if (fuzzface->activate_plugin !=0)
    fuzzface->activate_plugin(false, fuzzface);
  // delete DSP class
  fuzzface->delete_instance(fuzzface);
};

///////////////////////// PRIVATE CLASS  FUNCTIONS /////////////////////

void Gx_fuzzface_::init_dsp_(uint32_t rate)
{
  AVOIDDENORMALS(); // init the SSE denormal protection
  fuzzface->set_samplerate(rate, fuzzface); // init the DSP class
}

// connect the Ports used by the plug-in class
void Gx_fuzzface_::connect_(uint32_t port,void* data)
{
  switch ((PortIndex)port)
    {
    case EFFECTS_OUTPUT:
      output = static_cast<float*>(data);
      break;
    case EFFECTS_INPUT:
      input = static_cast<float*>(data);
      break;
    default:
      break;
    }
}

void Gx_fuzzface_::activate_f()
{
  // allocate the internal DSP mem
  if (fuzzface->activate_plugin !=0)
    fuzzface->activate_plugin(true, fuzzface);
}

void Gx_fuzzface_::clean_up()
{
  // delete the internal DSP mem
  if (fuzzface->activate_plugin !=0)
    fuzzface->activate_plugin(false, fuzzface);
}

void Gx_fuzzface_::deactivate_f()
{
  // delete the internal DSP mem
  if (fuzzface->activate_plugin !=0)
    fuzzface->activate_plugin(false, fuzzface);
}

void Gx_fuzzface_::run_dsp_(uint32_t n_samples)
{
  fuzzface->mono_audio(static_cast<int>(n_samples), input, output, fuzzface);
}

void Gx_fuzzface_::connect_all__ports(uint32_t port, void* data)
{
  // connect the Ports used by the plug-in class
  connect_(port,data); 
  // connect the Ports used by the DSP class
  fuzzface->connect_ports(port,  data, fuzzface);
}

////////////////////// STATIC CLASS  FUNCTIONS  ////////////////////////

LV2_Handle 
Gx_fuzzface_::instantiate(const LV2_Descriptor* descriptor,
                            double rate, const char* bundle_path,
                            const LV2_Feature* const* features)
{
  // init the plug-in class
  Gx_fuzzface_ *self = new Gx_fuzzface_();
  if (!self)
    {
      return NULL;
    }

  self->init_dsp_((uint32_t)rate);

  return (LV2_Handle)self;
}

void Gx_fuzzface_::connect_port(LV2_Handle instance, 
                                   uint32_t port, void* data)
{
  // connect all ports
  static_cast<Gx_fuzzface_*>(instance)->connect_all__ports(port, data);
}

void Gx_fuzzface_::activate(LV2_Handle instance)
{
  // allocate needed mem
  static_cast<Gx_fuzzface_*>(instance)->activate_f();
}

void Gx_fuzzface_::run(LV2_Handle instance, uint32_t n_samples)
{
  // run dsp
  static_cast<Gx_fuzzface_*>(instance)->run_dsp_(n_samples);
}

void Gx_fuzzface_::deactivate(LV2_Handle instance)
{
  // free allocated mem
  static_cast<Gx_fuzzface_*>(instance)->deactivate_f();
}

void Gx_fuzzface_::cleanup(LV2_Handle instance)
{
  // well, clean up after us
  Gx_fuzzface_* self = static_cast<Gx_fuzzface_*>(instance);
  self->clean_up();
  delete self;
}

const LV2_Descriptor Gx_fuzzface_::descriptor =
{
  GXPLUGIN_URI "#_fuzzface_",
  Gx_fuzzface_::instantiate,
  Gx_fuzzface_::connect_port,
  Gx_fuzzface_::activate,
  Gx_fuzzface_::run,
  Gx_fuzzface_::deactivate,
  Gx_fuzzface_::cleanup,
  NULL
};


} // end namespace fuzzface

////////////////////////// LV2 SYMBOL EXPORT ///////////////////////////

extern "C"
LV2_SYMBOL_EXPORT
const LV2_Descriptor*
lv2_descriptor(uint32_t index)
{
  switch (index)
    {
    case 0:
      return &fuzzface::Gx_fuzzface_::descriptor;
    default:
      return NULL;
    }
}

///////////////////////////// FIN //////////////////////////////////////
