#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    conf.sub_config('gxwmm');

def build(bld):
    bld.add_subdirs('gxwmm')
    bld(features = 'cxx cprogram',
        source = 'gxw_demo.cc',
        target = 'gxw_demo',
        uselib = 'GTKMM',
        includes = ['.','../libgxw'],
        uselib_local = ['gxwmm','gxw'],
        linkflags = "-Wl,-u,gxw_init",
        )
