#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    conf.recurse('gxwmm');

def build(bld):
    bld.recurse('gxwmm')
    bld.add_group()
    prog = bld(features = 'cxx cprogram',
               source = 'gxw_demo.cc',
               target = 'gxw_demo',
               use = ['GTKMM','gxwmm','gxw'],
               includes = ['.','../libgxw'],
               install_path = None,
               )
