#!/usr/bin/env python3
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gx_mbdistortion'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gx_mbdistortion.cpp'],
        includes = ['../faust','./', '../DSP'],
        cxxflags=['-fvisibility=hidden','-Wl,-z,noexecstack','-Wl,-z,relro,-z,now','-Wl,--exclude-libs,ALL'],
        use = ['LV2CORE'],
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gx_mbdistortion_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources',],
        cxxflags=['-fvisibility=hidden','-Wl,-z,noexecstack','-Wl,-z,relro,-z,now','-Wl,--exclude-libs,ALL'],
        use = ['xcairo','X11', 'CAIRO','LV2CORE'],
        )
